name: npm publish

on:
  push:
    tags:
      - 'v0.[0-9]+.[0-9]+-SNAPSHOT.[0-9]+'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - name: Check that KaitaiStream.js will be included
        run: |
          npm publish --tag next --dry-run --json | jq --exit-status '.files | map(.path) | any(. == "KaitaiStream.js")'
      - name: Publish to npm
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
