name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  build:

    strategy:
      matrix:
        # The first supported and avaable for testing, LTS and latest
        node-version: [12, lts, latest]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
